recipe: default.v1
assistant_id: 20250513-144244-sad-lighthouse
language: en

pipeline:
  - name: WhitespaceTokenizer # Split into tokens by white space
  - name: RegexFeaturizer # Allows for regex-based features
    use_regexes: true
    use_lexical_syntactic_features: true
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper # Maps synonym entities
  - name: DucklingEntityExtractor
    url: http://duckling:8000
    dimensions: ["amount-of-money", "time", "number"]
  - name: FallbackClassifier
    threshold: 0.3

policies:
  - name: "RulePolicy"
